### ISSUE TITLE
Constant errors by reproducing pcmb_kang

### ISSUE THREAD

**Issue by Luneesh** [theislab/expiMap_reproducibility#26]
Dear authors,

As part of the Bpexa project of the Bioinformatics Faculty at Hogeschool Leiden, where students collaborate with various organizations and companies to gain their first experience in the field, we have been assigned the task of replicating Figure 2 from your paper, ["Biologically informed deep learning to query gene programs in single-cell atlases"](https://www.nature.com/articles/s41556-022-01072-x#Abs1), which, as we understand, is represented in the *pmbc_kang* directory.

The task was given to us by curators. However, while attempting to run the code, we encountered numerous issues, primarily related to constant errors thrown by the scripts, mostly when using the *scArches* module. We are stuck at the notebook script `model_training_for_figures_2_3.ipynb`.

It seems that either certain functions are being called incorrectly, or *scArches* methods are receiving extra attributes that do not exist in its code. This raises the question: Are we using the correct version of *scArches*? At this point, it seems the code is not easily replicable.

**Comment by Koncopd** [comment]
Hello, @Luneesh 
in the readme file we reference the branch that is used for scripts and notebooks here
it is https://github.com/theislab/scarches/tree/soft_new_mask

**Comment by Koncopd** [comment]
To use the latest API, you can also check https://github.com/theislab/scarches/blob/master/notebooks/expimap_surgery_pipeline_basic.ipynb
This uses the same data as in `model_training_for_figures_2_3.ipynb`

**Comment by Luneesh** [comment]
> Hello, @Luneesh in the readme file we reference the branch that is used for scripts and notebooks here it is https://github.com/theislab/scarches/tree/soft_new_mask

Hello, thank you for your response. I tried this option earlier today, but it led to a couple of errors due to more modern libraries — currently, the problem is with SciPy. Version 0.14.1 no longer supports the `itemfreq` function.

Most likely, I’ll need to experiment with versions, because after rolling back to 0.14.0, my PC somehow ignores or incorrectly installs scarches itself — but it might be an issue on my end.

Still, I’ll try your suggestion regarding the more modern API.  Аnyway thanks for the help

**Comment by Koncopd** [comment]
[soft_new_mask.txt](https://github.com/user-attachments/files/17100904/soft_new_mask.txt)
This is my old environment that can run the notebook with the old branch (soft_new_mask), a lot of irrelevant stuff there, but maybe might help with some versions.

**Comment by Luneesh** [comment]
Thanks again for your help)

**Comment by Luneesh** [comment]
Apologies for reopening the issue and for taking up your time. We as a group are very grateful for your response, as it helped us make progress in the project. We were able to generate the necessary kang_pbmc_integrated file. However, when we proceeded to work with the scripts that generate the plots for Figure 2—specifically in the notebook [pbmc_kang/figure_2e_supp_figures_2_3.ipynb](https://github.com/theislab/expiMap_reproducibility/blob/main/pbmc_kang/figure_2e_supp_figures_2_3.ipynb), we encountered a problem with the scArches package version, realizing that we still need to use an older version.

Thank you for providing the environment file. Unfortunately, when we tried to create the environment, the system got stuck in an infinite loop. From what I understand, the system might be trying to install packages with conflicting versions, leading to this issue.

Could you please assist us with this problem? I'll also try to manually install the necessary packages, but I'm unsure if that will solve the issue.

Thank you again for your help!

**Comment by Koncopd** [comment]
Hi, in the tutorial i referenced it is shown to use `latent_directions`, `latent_enrich` and `plotting.plot_abs_bfs` of the new version. The other parts should be mostly the same.

**Comment by Koncopd** [comment]
I don't think the environment file i provided can be used directly, but rather only to the the versions of the dependencies of the old branch of scarches maybe.
